<a href="https://colab.research.google.com/github/Fsrkh/machine-learning-small-projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
b = np.ones((30))
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
b= b.reshape(3,10)
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
b.dtype

dtype('float64')

In [9]:
c = np.random.randn(5,6)
c

array([[-2.31761566, -0.48372691,  0.4614417 ,  1.40071834, -0.25703279,
         0.32011213],
       [-0.12885247,  0.56081564,  0.31584396, -0.75310525,  0.8955116 ,
         0.14871238],
       [ 0.4886465 ,  0.36468024,  0.62426285,  1.20857055, -1.06122779,
         0.97534782],
       [-1.35924367, -0.62715074,  0.82539739, -0.43758709, -0.55116994,
         0.68839726],
       [ 0.79026694, -0.77280987, -0.13230656,  0.43210807, -0.31180949,
         0.14400533]])